language: cpp

services:
  - docker

before_install:
  - docker pull atlasamglab/stats
  - docker run --rm -it atlasamglab/stats

script:
  - pwd
  - mkdir build
  - cd build
  - cmake ../ && make -j
