language: cpp

services:
  - docker

before_install:
  - docker pull atlasamglab/stats
  - docker run --name atlasroot -d atlasamglab/stats
  - docker ps -a

script:
  - pwd && ls
  - docker exec -it atlasroot /bin/bash
  - mkdir build
  - cd build
  - cmake ../ && make -j
