language: cpp

services:
  - docker

before_install:
  - docker pull atlasamglab/stats
  - docker run -d atlasamglab/stats /bin/bash
  - docker ps -a
  - docker run atlasamglab/stats /bin/bash

script:
  - pwd && ls
  - mkdir build
  - cd build
  - cmake ../ && make -j
