sudo: required

language: cpp

services:
  - docker
  
env: SH="docker run -t atlasamglab/stats:latest /bin/bash -c"

before_install:
  - docker run -d --name atlasroot -v $(pwd):/travis -w /travis atlasamglab/stats:latest tail -f /dev/null
  - docker ps -a

install:
  - ${SH} "which root"
  - ${SH} "mkdir build && cd build"
  - ${SH} "cmake ../ && make -j"

script:
  - ls *
