#include <string>

void test_hadhad(const std::string& filename);
void test_hadhad_klambda(const std::string& filename);
void test_hadhad_yield(const std::string& filename);
void test_hadhad_ZtautauMG(const std::string& filename);
void test_hadhad_ZtautauUnc1(const std::string& filename);
void test_hadhad_ZtautauUnc2(const std::string& filename);
void test_hadhad_ZtautauUnc3(const std::string& filename);
void test_hadhad_ZtautauRew(const std::string& filename);
void test_hadhad_WtDS(const std::string& filename);
void test_hadhad_WtGen(const std::string& filename);
void test_hadhad_WtOTF(const std::string& filename);
void test_hadhad_NonRes(const std::string& filename);
void test_hadhad_ttbarSys_OTF(const std::string& filename);
void test_hadhad_ttbarSys_Gen(const std::string& filename);
void test_lephad_ttbarSys(const std::string& filename);
void test_lephad_ttbarRew(const std::string& filename);
void test_hadhad_ttbarRew(const std::string& filename);
void test_ttbarKine(const std::string& filename);
void test_bbll(const std::string& filename);
void test_check_syst(const std::string& filename);

void hadhadsr_v15(const std::string& filename);
void hadhadsr_v15_yield(const std::string& filename);
void hadhadsr_v15_binning(const std::string& filename);

void thesis_mvainput(const std::string& filename);
void thesis_mvaoutput(const std::string& filename);
void thesis_overfit(const std::string& filename);
void thesis_binning(const std::string& filename);
void thesis_zcr(const std::string& filename);
void thesis_ttbarsf(const std::string& filename);
void thesis_zvr(const std::string& filename);
void thesis_zvr_2tag(const std::string& filename);
void thesis_sr(const std::string& filename);
void thesis_sr_ws_bdt(const std::string& filename, bool prefit=true);
void thesis_sr_ws_pnn(const std::string& filename, const std::string& mass, bool prefit=true);
void thesis_sr_lephad_ws_bdt(const std::string& filename, bool prefit=true, bool SLT=true);
void thesis_sr_lephad_ws_pnn(const std::string& filename, const std::string& mass, bool prefit=true, bool SLT=true);
void thesis_mjvr(const std::string& filename);
void thesis_mjvr_2bss(const std::string& filename);
void thesis_ttbarvr(const std::string& filename);
void thesis_ffcr(const std::string& filename);
void thesis_ffcr_2tag(const std::string& filename);
void thesis_ffcr_closure(const std::string& filename);
void thesis_syst_zhf(const std::string& filename);
void thesis_syst_zhf_param_mg(const std::string& filename);
void thesis_syst_zhf_param_scale(const std::string& filename);
void thesis_syst_ttbar(const std::string& filename);
void thesis_syst_stop(const std::string& filename);
void thesis_syst_stop_param_topint(const std::string& filename);
void thesis_sr_ws_lastbin(const std::string& filename, const std::string& mass, const std::string& region);
void thesis_sr_ws_input(const std::string& filename);
void thesis_sr_ws_bdt_klam(const std::string& filename, bool prefit);
void test_bukin_binning(const std::string& filename);
