#ifndef DRAWSTACKTOOL_WS_H
#define DRAWSTACKTOOL_WS_H

#include "DrawStackTool.h"
#include "CommonInclude_WS.h"

#include <string>
#include <vector>
#include <iterator>

using std::string;
using std::vector;

/**
 * This tool is the WS version of the classic DrawStackTool
 * it draws stack, data-mc comparisons using the file generated by
 * WorkspaceToRoot.cpp
 * In this sense, it is still a HistTool.
 * 
 * Use with caution! see notes below
 * 
 * @note 
 * in this tool, draw_overflow option might not work for data 
 * becasue it was not filled in the RooHist
 */
class DrawStackTool_WS : public DrawStackTool
{
public:
    explicit DrawStackTool_WS(const DrawStackInfo* info);
    virtual ~DrawStackTool_WS() override;

public:
    // drawing
    virtual void run(const Config* c) const override;
};

#endif // DRAWSTACKTOOL_H
