name: CMake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: rootproject/root:6.22.06-ubuntu20.04

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ls $GITHUB_WORKSPACE && cmake .

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ls . && pwd && make
